name: Create DynamoDB Local Tables
description: Creates the SudokuGames and SudokuPlayers DynamoDB tables in a running DynamoDB Local instance

runs:
  using: composite
  steps:
    - name: Create DynamoDB tables in LocalStack
      shell: bash
      run: |
        aws --endpoint-url=http://localhost:8000 dynamodb create-table \
          --table-name SudokuGames \
          --attribute-definitions AttributeName=userId,AttributeType=S AttributeName=gameId,AttributeType=S \
          --key-schema AttributeName=userId,KeyType=HASH AttributeName=gameId,KeyType=RANGE \
          --billing-mode PAY_PER_REQUEST \
          --region us-east-1

        aws --endpoint-url=http://localhost:8000 dynamodb create-table \
          --table-name SudokuPlayers \
          --attribute-definitions AttributeName=userId,AttributeType=S \
          --key-schema AttributeName=userId,KeyType=HASH \
          --billing-mode PAY_PER_REQUEST \
          --region us-east-1
      env:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: us-east-1
