quarkus.http.root-path=/api/v1

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=Content-Type,Accept

mp.openapi.scan.disable=true
quarkus.swagger-ui.always-include=false
